### ISSUE TITLE
TypeError: unsupported operand type(s)

### ISSUE THREAD

**Issue by jjang750** [ec-blaster/pyMagicSwitchbot#6]
Hello
I'm trying to use your MagicSwitchbot package, but there's an error and it's not working anymore.
Please check.

-------------------
test.py

from magicswitchbot import MagicSwitchbot
import time, logging

logging.basicConfig(level=logging.DEBUG)

MAC = "34:14:b5:4a:39:b3" #my device

device = MagicSwitchbot(mac=MAC, connect_timeout=15, disconnect_timeout=10, password=None)

print(f"Connecting to MagicSwitchbot device at {MAC}...")

exit(1)

-------------------

Traceback (most recent call last):
  File "/root/test.py", line 2, in <module>
    from magicswitchbot import MagicSwitchbot
  File "/usr/local/lib/python3.9/dist-packages/magicswitchbot/__init__.py", line 15, in <module>
    from .device import MagicSwitchbotDevice
  File "/usr/local/lib/python3.9/dist-packages/magicswitchbot/device.py", line 53, in <module>
    class MagicSwitchbotDevice:
  File "/usr/local/lib/python3.9/dist-packages/magicswitchbot/device.py", line 59, in MagicSwitchbotDevice
    password: str | None=None,
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

-------------------------------
pyMagicSwitchbot updated!!

pyMagicSwitchbot in /usr/local/lib/python3.9/dist-packages (1.1.4)

**Comment by ec-blaster** [comment]
Hello.

I can see you are using Python 3.9, but pyMagicSwitchbot requires 3.10.
The error you are getting is because Python 3.9 does not support that "unions type" syntax. You can read about it at [this link](https://www.blog.pythonlibrary.org/2021/09/11/python-3-10-simplifies-unions-in-type-annotations/).

Sorry
